[colors.primary]
background = "0x1e1e2e"
foreground = "0xcdd6f4"

[cursor]
style = "Beam"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
size = 12.5

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "full"
dynamic_padding = true
opacity = 0.85

[window.padding]
x = 10
y = 10
